--liquibase formatted sql
--changeset manhc:1
INSERT INTO city (name, code) VALUES
                                  ('An Giang', 'AG'),
                                  ('Bắc Ninh', 'BN'),
                                  ('Cà Mau', 'CM'),
                                  ('Cần Thơ', 'CT'),
                                  ('Cao Bằng', 'CB'),
                                  ('Đà Nẵng', 'DN'),
                                  ('Đắk Lắk', 'DL'),
                                  ('Điện Biên', 'DB'),
                                  ('Đồng Nai', 'DON'),
                                  ('Đồng Tháp', 'DT'),
                                  ('Gia Lai', 'GL'),
                                  ('Hà Nội', 'HN'),
                                  ('Hà Tĩnh', 'HT'),
                                  ('Hải Phòng', 'HP'),
                                  ('Hưng Yên', 'HY'),
                                  ('Khánh Hòa', 'KH'),
                                  ('Lai Châu', 'LC'),
                                  ('Lâm Đồng', 'LD'),
                                  ('Lạng Sơn', 'LS'),
                                  ('Lào Cai', 'LCA'),
                                  ('Nghệ An', 'NA'),
                                  ('Ninh Bình', 'NB'),
                                  ('Phú Thọ', 'PT'),
                                  ('Quảng Ngãi', 'QNG'),
                                  ('Quảng Ninh', 'QN'),
                                  ('Quảng Trị', 'QT'),
                                  ('Sơn La', 'SL'),
                                  ('Tây Ninh', 'TN'),
                                  ('Thái Nguyên', 'TNG'),
                                  ('Thanh Hóa', 'TH'),
                                  ('Thành phố Hồ Chí Minh', 'HCM'),
                                  ('Tuyên Quang', 'TQ'),
                                  ('Vĩnh Long', 'VL'),
                                  ('Huế', 'HUE');