spring:
  application:
    name: auth-service

  cloud:
    config:
      enabled: false

  security:
    oauth2:
      resource server:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCE_SERVER_JWT_URI:http://localhost:8000/auth/.well-known/jwks.json}

  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Manh2004}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/auth}

  liquibase:
    change-log: classpath:/db/changelog/appchange-log.xml
    liquibase-schema: ${LIQUIBASE_SCHEMA:auth}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: none

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}

private_key:
  path: ${PRIVATE_KEY_PATH:D:\workspace\bus-booking-system\auth-service\private.pem}

public_key:
  path: ${PUBLIC_KEY_PATH:D:\workspace\bus-booking-system\auth-service\public.pem}

service:
  users:
    url: ${SERVICE_USERS_URL:http://localhost:8001/users}

server:
  port: 8000
