spring:
  application:
    name: api-gateway

  cloud:
    config:
      enabled: false
    gateway:
      httpclient:
        pool:
          type: ELASTIC
          max-idle-time: 15s
          max-connections: 1000
      server:
        webflux:
          httpclient:
            pool:
              type: ELASTIC
              max-idle-time: 15s
              max-connections: 1000
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  security:
    oauth2:
      resource server:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCE_SERVER_JWT_URI:http://localhost:8000/auth/.well-known/jwks.json}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}

logging:
  level:
    root: INFO
    org.springframework.security: INFO

frontend:
  url: ${FRONTEND_URL:http://localhost:3000}
